-- ================================================================
-- INSTALL_SENSOR_NAMES.sql
-- Jalankan di database pln_web (bukan db_pacitan_1)
-- Membuat tabel sensor_tags dari address.xlsx dan mengisinya.
-- Setelah ini, PHP akan auto-detect nama sensor dari tag ID.
-- ================================================================

USE pln_web;

CREATE TABLE IF NOT EXISTS sensor_tags (
    tag_id      INT NOT NULL PRIMARY KEY,
    deskripsi   VARCHAR(255) NOT NULL,
    satuan      VARCHAR(20) DEFAULT '',
    singkatan   VARCHAR(100) DEFAULT '',  -- nama pendek untuk UI
    address_no  VARCHAR(200) DEFAULT '',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert semua sensor dari address.xlsx
-- ON DUPLICATE KEY UPDATE: aman dijalankan ulang
INSERT INTO sensor_tags (tag_id, deskripsi, satuan, singkatan) VALUES
(331,  'FDF A NON DRIVED END BEARING TEMPERATURE 1',        'C',    'FDF A NDE Brg Temp 1'),
(1860, 'FDF A NON DRIVED END BEARING TEMPERATURE 3',        'C',    'FDF A NDE Brg Temp 3'),
(1858, 'FDF A CURRENT',                                      'A',    'FDF A Current'),
(595,  'FDF A NON DRIVED END BEARING VIBRATING ON X',       'mm/s', 'FDF A NDE Vib-X'),
(598,  'FDF A MOTOR STATOR COIL U TEMPERATURE 2',           'C',    'FDF A Coil U Temp 2'),
(1625, 'FDF A MOTOR DRIVING END BEARING TEMPERATURE',       'C',    'FDF A Motor DE Brg Temp'),
(849,  'FDF A MOTOR NON DRIVING END BEARING TEMPERATURE',   'C',    'FDF A Motor NDE Brg Temp'),
(1644, 'FDF A INLET AIR TEMPERATURE',                       'C',    'FDF A Inlet Air Temp'),
(1620, 'FDF A DRIVED END BEARING VIBRATING ON X',          'mm/s', 'FDF A DE Vib-X'),
(1350, 'FDF A DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'FDF A DE Vib-Y'),
(845,  'FDF A NON DRIVED END BEARING VIBRATING ON Y',      'mm/s', 'FDF A NDE Vib-Y'),
(1090, 'FDF A MOTOR STATOR COIL V TEMPERATURE 2',           'C',    'FDF A Coil V Temp 2'),
(1627, 'FDF A NON DRIVED END BEARING TEMPERATURE 2',        'C',    'FDF A NDE Brg Temp 2'),
(850,  'FDF A DRIVED END BEARING TEMPERATURE 3',            'C',    'FDF A DE Brg Temp 3'),
(1624, 'FDF A MOTOR STATOR COIL U TEMPERATURE 1',           'C',    'FDF A Coil U Temp 1'),
(1352, 'FDF A MOTOR STATOR COIL V TEMPERATURE 1',           'C',    'FDF A Coil V Temp 1'),
(599,  'FDF A MOTOR STATOR COIL W TEMPERATURE 2',           'C',    'FDF A Coil W Temp 2'),
(1626, 'FDF A DRIVED END BEARING TEMPERATURE 1',            'C',    'FDF A DE Brg Temp 1'),
(332,  'FDF A DRIVED END BEARING TEMPERATURE 2',            'C',    'FDF A DE Brg Temp 2'),
(1359, 'FDF A OUTLET AIR PRESSURE',                         'KPa',  'FDF A Outlet Air Press'),
(527,  'FDF A INLET VANE CONTROL COMMAND',                  '%',    'FDF A Vane Command'),
(539,  'FDF A INLET VANE POSITION',                         '%',    'FDF A Vane Position'),
(81,   'FDF A MOTOR STATOR COIL W TEMPERATURE 1',           'C',    'FDF A Coil W Temp 1'),
(605,  'FDF B MOTOR STATOR COIL V TEMPERATURE 2',           'C',    'FDF B Coil V Temp 2'),
(1103, 'FDF B NON DRIVED END BEARING TEMPERATURE 3',        'C',    'FDF B NDE Brg Temp 3'),
(1104, 'FDF B DRIVED END BEARING TEMPERATURE 3',            'C',    'FDF B DE Brg Temp 3'),
(87,   'FDF B MOTOR STATOR COIL W TEMPERATURE 2',           'C',    'FDF B Coil W Temp 2'),
(1356, 'FDF B NON DRIVED END BEARING TEMPERATURE 2',        'C',    'FDF B NDE Brg Temp 2'),
(86,   'FDF B MOTOR STATOR COIL U TEMPERATURE 1',           'C',    'FDF B Coil U Temp 1'),
(341,  'FDF B MOTOR STATOR COIL V TEMPERATURE 1',           'C',    'FDF B Coil V Temp 1'),
(604,  'FDF B NON DRIVED END BEARING TEMPERATURE 1',        'C',    'FDF B NDE Brg Temp 1'),
(1867, 'FDF B MOTOR NON DRIVING END BEARING TEMPERATURE',   'C',    'FDF B Motor NDE Brg Temp'),
(1640, 'FDF B OUTLET AIR PRESSURE',                         'KPa',  'FDF B Outlet Air Press'),
(1862, 'FDF B DRIVED END BEARING VIBRATING ON X',          'mm/s', 'FDF B DE Vib-X'),
(1355, 'FDF B MOTOR DRIVING END BEARING TEMPERATURE',       'C',    'FDF B Motor DE Brg Temp'),
(1865, 'FDF B MOTOR STATOR COIL W TEMPERATURE 1',           'C',    'FDF B Coil W Temp 1'),
(88,   'FDF B DRIVED END BEARING TEMPERATURE 2',            'C',    'FDF B DE Brg Temp 2'),
(1308, 'FDF B INLET VANE POSITION',                         '%',    'FDF B Vane Position'),
(602,  'FDF B CURRENT',                                      'A',    'FDF B Current'),
(1864, 'FDF B NON DRIVED END BEARING VIBRATING ON Y',      'mm/s', 'FDF B NDE Vib-Y'),
(1810, 'FDF B INLET VANE CONTROL COMMAND',                  '%',    'FDF B Vane Command'),
(1863, 'FDF B NON DRIVED END BEARING VIBRATING ON X',      'mm/s', 'FDF B NDE Vib-X'),
(338,  'FDF B DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'FDF B DE Vib-Y'),
(1866, 'FDF B DRIVED END BEARING TEMPERATURE 1',            'C',    'FDF B DE Brg Temp 1'),
(1102, 'FDF B MOTOR STATOR COIL U TEMPERATURE 2',           'C',    'FDF B Coil U Temp 2'),
(351,  'FDF B INLET AIR TEMPERATURE',                       'C',    'FDF B Inlet Air Temp'),
(1351, 'IDF A NON DRIVED END BEARING VIBRATING ON X',      'mm/s', 'IDF A NDE Vib-X'),
(1623, 'IDF A DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'IDF A DE Vib-Y'),
(1859, 'IDF A #2 COOLING FAN MOTOR CURRENT',               'A',    'IDF A #2 Fan Current'),
(1092, 'IDF A MOTOR STATOR COIL V TEMPERATURE 1',           'C',    'IDF A Coil V Temp 1'),
(1861, 'IDF A MOTOR DRIVING END BEARING TEMPERATURE',       'C',    'IDF A Motor DE Brg Temp'),
(1645, 'IDF A OUTLET FLUE GAS TEMPERATURE',                 'C',    'IDF A Outlet Gas Temp'),
(79,   'IDF A CURRENT',                                      'A',    'IDF A Current'),
(1628, 'IDF A MIDDLE BEARING TEMPERATURE 1',                'C',    'IDF A Middle Brg Temp 1'),
(1630, 'IDF A NON DRIVED END BEARING TEMPERATURE 1',        'C',    'IDF A NDE Brg Temp 1'),
(1364, 'ESP A OUTLET FLUE GAS PRESSURE',                    'Pa',   'ESP A Outlet Gas Press'),
(1309, 'IDF A INLET STATIONARY BLADE POSITION',             '%',    'IDF A Blade Position'),
(1089, 'IDF A DRIVED END BEARING VIBRATING ON X',          'mm/s', 'IDF A DE Vib-X'),
(1629, 'IDF A MIDDLE BEARING TEMPERATURE 2',                'C',    'IDF A Middle Brg Temp 2'),
(334,  'IDF A MOTOR STATOR COIL U TEMPERATURE 2',           'C',    'IDF A Coil U Temp 2'),
(335,  'IDF A MOTOR NON DRIVING END BEARING TEMPERATURE',   'C',    'IDF A Motor NDE Brg Temp'),
(853,  'IDF A DRIVED END BEARING TEMPERATURE 2',            'C',    'IDF A DE Brg Temp 2'),
(862,  'IDF A OUTLET FLUE GAS PRESSURE',                    'Pa',   'IDF A Outlet Gas Press'),
(531,  'IDF A INLET STATIONARY BLADE CONTROL COMMAND',      '%',    'IDF A Blade Command'),
(600,  'IDF A NON DRIVED END BEARING TEMPERATURE 2',        'C',    'IDF A NDE Brg Temp 2'),
(1093, 'IDF A MOTOR STATOR COIL W TEMPERATURE 1',           'C',    'IDF A Coil W Temp 1'),
(847,  'IDF A NON DRIVED END BEARING VIBRATING ON Y',      'mm/s', 'IDF A NDE Vib-Y'),
(80,   'IDF A #1 COOLING FAN MOTOR CURRENT',               'A',    'IDF A #1 Fan Current'),
(601,  'IDF A MOTOR STATOR COIL U TEMPERATURE 1',           'C',    'IDF A Coil U Temp 1'),
(1095, 'IDF A MOTOR STATOR COIL V TEMPERATURE 2',           'C',    'IDF A Coil V Temp 2'),
(852,  'IDF A MOTOR STATOR COIL W TEMPERATURE 2',           'C',    'IDF A Coil W Temp 2'),
(1094, 'IDF A DRIVED END BEARING TEMPERATURE 1',            'C',    'IDF A DE Brg Temp 1'),
(879,  'ESP A OUTLET FLUE GAS TEMPERATURE',                 'C',    'ESP A Outlet Gas Temp'),
(856,  'IDF B #1 COOLING FAN MOTOR CURRENT',               'A',    'IDF B #1 Fan Current'),
(606,  'IDF B NON DRIVED END BEARING TEMPERATURE 2',        'C',    'IDF B NDE Brg Temp 2'),
(1357, 'IDF B MOTOR DRIVING END BEARING TEMPERATURE',       'C',    'IDF B Motor DE Brg Temp'),
(1369, 'IDF B OUTLET FLUE GAS TEMPERATURE',                 'C',    'IDF B Outlet Gas Temp'),
(336,  'IDF B CURRENT',                                      'A',    'IDF B Current'),
(860,  'IDF B MOTOR STATOR COIL U TEMPERATURE 2',           'C',    'IDF B Coil U Temp 2'),
(1358, 'IDF B DRIVED END BEARING TEMPERATURE 2',            'C',    'IDF B DE Brg Temp 2'),
(610,  'IDF B OUTLET FLUE GAS PRESSURE',                    'Pa',   'IDF B Outlet Gas Press'),
(1107, 'IDF B MOTOR STATOR COIL V TEMPERATURE 1',           'C',    'IDF B Coil V Temp 1'),
(90,   'IDF B MOTOR STATOR COIL W TEMPERATURE 2',           'C',    'IDF B Coil W Temp 2'),
(1106, 'IDF B MIDDLE BEARING TEMPERATURE 2',                'C',    'IDF B Middle Brg Temp 2'),
(89,   'IDF B MOTOR STATOR COIL V TEMPERATURE 2',           'C',    'IDF B Coil V Temp 2'),
(85,   'IDF B DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'IDF B DE Vib-Y'),
(1101, 'IDF B NON DRIVED END BEARING VIBRATING ON Y',      'mm/s', 'IDF B NDE Vib-Y'),
(1868, 'IDF B NON DRIVED END BEARING TEMPERATURE 1',        'C',    'IDF B NDE Brg Temp 1'),
(859,  'IDF B DRIVED END BEARING TEMPERATURE 1',            'C',    'IDF B DE Brg Temp 1'),
(858,  'IDF B MOTOR STATOR COIL W TEMPERATURE 1',           'C',    'IDF B Coil W Temp 1'),
(342,  'IDF B MOTOR STATOR COIL U TEMPERATURE 1',           'C',    'IDF B Coil U Temp 1'),
(532,  'IDF B INLET STATIONARY BLADE CONTROL COMMAND',      '%',    'IDF B Blade Command'),
(543,  'IDF B INLET STATIONARY BLADE POSITION',             '%',    'IDF B Blade Position'),
(1100, 'IDF B NON DRIVED END BEARING VIBRATING ON X',      'mm/s', 'IDF B NDE Vib-X'),
(1105, 'IDF B MIDDLE BEARING TEMPERATURE 1',                'C',    'IDF B Middle Brg Temp 1'),
(882,  'ESP B OUTLET FLUE GAS TEMPERATURE',                 'C',    'ESP B Outlet Gas Temp'),
(1353, 'PAF A MOTOR STATOR V TEMPERATURE',                  'C',    'PAF A Stator V Temp'),
(1575, 'PAF A INLET VANE POSITION',                         '%',    'PAF A Vane Position'),
(329,  'PAF A CURRENT',                                      'A',    'PAF A Current'),
(596,  'PAF A NON DRIVED END BEARING VIBRATING ON X',      'mm/s', 'PAF A NDE Vib-X'),
(851,  'PAF A MOTOR STATOR W TEMPERATURE',                  'C',    'PAF A Stator W Temp'),
(877,  'PAF A INLET AIR TEMPERATURE',                       'C',    'PAF A Inlet Air Temp'),
(1091, 'PAF A MOTOR DRIVING END BEARING TEMPERATURE',       'C',    'PAF A Motor DE Brg Temp'),
(597,  'PAF A DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'PAF A DE Vib-Y'),
(846,  'PAF A DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'PAF A DE Vib-Y 2'),
(1565, 'PAF A INLET VANE CONTROL COMMAND',                  '%',    'PAF A Vane Command'),
(1622, 'PAF A DRIVED END BEARING VIBRATING ON X',          'mm/s', 'PAF A DE Vib-X'),
(1870, 'PAF A OUTLET AIR PRESSURE',                         'KPa',  'PAF A Outlet Air Press'),
(333,  'PAF A NON DRIVED END BEARING TEMPERATURE',          'C',    'PAF A NDE Brg Temp'),
(1631, 'PAF A MOTOR NON DRIVING END BEARING TEMPERATURE',   'C',    'PAF A Motor NDE Brg Temp'),
(848,  'PAF A MOTOR STATOR U TEMPERATURE',                  'C',    'PAF A Stator U Temp'),
(1632, 'PAF A DRIVED END BEARING TEMPERATURE',              'C',    'PAF A DE Brg Temp'),
(1638, 'PAF B MOTOR STATOR W TEMPERATURE',                  'C',    'PAF B Stator W Temp'),
(1869, 'PAF B MOTOR DRIVING END BEARING TEMPERATURE',       'C',    'PAF B Motor DE Brg Temp'),
(854,  'PAF B DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'PAF B DE Vib-Y'),
(1108, 'PAF B DRIVED END BEARING TEMPERATURE',              'C',    'PAF B DE Brg Temp'),
(82,   'PAF B CURRENT',                                      'A',    'PAF B Current'),
(1099, 'PAF B DRIVED END BEARING VIBRATING ON X',          'mm/s', 'PAF B DE Vib-X'),
(284,  'PAF B INLET VANE POSITION',                         '%',    'PAF B Vane Position'),
(1637, 'PAF B MOTOR STATOR V TEMPERATURE',                  'C',    'PAF B Stator V Temp'),
(20,   'PAF B INLET VANE CONTROL COMMAND',                  '%',    'PAF B Vane Command'),
(855,  'PAF B DRIVED END BEARING VIBRATING ON Y',          'mm/s', 'PAF B DE Vib-Y 2'),
(857,  'PAF B MOTOR STATOR U TEMPERATURE',                  'C',    'PAF B Stator U Temp'),
(1354, 'PAF B NON DRIVED END BEARING VIBRATING ON X',      'mm/s', 'PAF B NDE Vib-X'),
(1363, 'PAF B OUTLET AIR PRESSURE',                         'KPa',  'PAF B Outlet Air Press'),
(607,  'PAF B NON DRIVED END BEARING TEMPERATURE',          'C',    'PAF B NDE Brg Temp'),
(343,  'PAF B MOTOR NON DRIVING END BEARING TEMPERATURE',   'C',    'PAF B Motor NDE Brg Temp'),
(616,  'PAF B INLET AIR TEMPERATURE',                       'C',    'PAF B Inlet Air Temp'),
(1577, 'UNIT LOAD',                                          'MW',   'Unit Load')
ON DUPLICATE KEY UPDATE
    deskripsi = VALUES(deskripsi),
    satuan    = VALUES(satuan),
    singkatan = VALUES(singkatan);

-- Tambah juga bearing_models jika belum ada
CREATE TABLE IF NOT EXISTS bearing_models (
    model_id        INT AUTO_INCREMENT PRIMARY KEY,
    tagno           VARCHAR(20) NOT NULL,
    bearing_label   VARCHAR(10) DEFAULT 'Y1',
    model_name      VARCHAR(255),
    model_type      VARCHAR(50),
    train_start     DATE,
    train_end       DATE,
    n_train         INT DEFAULT 0,
    r2_score        DOUBLE DEFAULT 0,
    coef_a          DOUBLE DEFAULT 0,
    coef_b          DOUBLE DEFAULT 0,
    threshold       DOUBLE DEFAULT 5.0,
    total_anomalies INT DEFAULT 0,
    unit_id         INT,
    plant_id        INT,
    unit_db         VARCHAR(100),
    source_file     VARCHAR(255),
    model_path      VARCHAR(500),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Verifikasi
SELECT COUNT(*) AS total_sensor_tags FROM sensor_tags;
SELECT COUNT(*) AS total_models FROM bearing_models;
